general:
  cfApiEndpoint: 'https://api.cf.sap.hana.ondemand.com'
  cfOrg: 'myOrg'
  cfSpace: 'mySpace'
  cfCredentialsId: 'cfAuthentification'
  cfServiceInstance: 'atc_system'
  cfServiceKeyName: 'JENKINS_SAP_COM_0510'
stages:
  Prepare System:
    cfService: 'abap'
    cfServicePlan: 'standard'
    abapSystemAdminEmail: 'user@example.com'
    abapSystemDescription: 'ABAP Environment Q System'
    abapSystemIsDevelopmentAllowed: false
    abapSystemID: 'H02'
    abapSystemSizeOfPersistence: 4
    abapSystemSizeOfRuntime: 1
    cfServiceKeyConfig: 'serviceKey.json'
  Clone Repositories:
    repositories: 'repositories.yml'
    strategy: 'Clone'
  ATC:
    atcConfig: 'atcConfig.yml'
  Post:
    confirmDeletion: true
steps:
  cloudFoundryDeleteService:
    cfDeleteServiceKeys: true
